### ISSUE TITLE
Copy default configuration to users home if it does not exist.

### ISSUE THREAD

**Issue by StoneyJackson** [GNOME-MouseTrap/mousetrap#32]
Right now we ask users to make a copy of the default configuration themselves. They shouldn't have to dig through */site-packages/mousetrap/..  to get it. We should populate ~/.mousetrap.yaml automatically if it is not there.

**Comment by kevin-brown** [comment]
I'm currently -1 on this because it has introduced a few unintended problems and I've never seen it done this way before.

Right now when MouseTrap is run, the file is automatically copied to the home directory.  This is the first time I've seen a program do this without prompting the user, or without the user completing an action that would prompt it.  While I agree that forcing users to copy the entire file can be seen as an annoyance, especially if they have to copy the entire thing, moving files around without prompting users might be worse.

This has an additional problem where the file is automatically copied when running the `distcheck` command, most likely because of the tests.

A possible solution would be to move this to a command line argument.

**Comment by StoneyJackson** [comment]
Add two command-line options,
- [x] `--dump-config`  Loads and dumps to standard out MouseTraps configuration
- [x] `--config-file=FILE`  Loads configuration from specified file.
